# Generated by Django 5.1.1 on 2024-12-11 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userachievement_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed School', help_text='Название школы.', max_length=255, unique=True)),
                ('address', models.CharField(default='No Address Provided', help_text='Адрес школы.', max_length=500)),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон школы.', max_length=20, null=True)),
                ('email', models.EmailField(default='admin@school.com', help_text='Электронная почта школы.', max_length=254, unique=True)),
                ('website', models.URLField(blank=True, help_text='Веб-сайт школы.', null=True)),
                ('established_date', models.DateField(blank=True, help_text='Дата основания школы.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='advisers',
            field=models.ManyToManyField(blank=True, help_text='Учителя, ответственные за класс.', limit_choices_to={'role': 'teacher'}, related_name='advised_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(default='No description provided.', help_text='Описание достижения.'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, default='achievements/icons/default_icon.png', help_text='Иконка достижения.', null=True, upload_to='achievements/icons/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='Unnamed Achievement', help_text='Название достижения.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата посещаемости.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Примечания к посещаемости.', null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='Unnamed Class', help_text='Название класса, например, 5А.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Комментарии учителя к оценке.', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Оценка студента.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(default='No description provided.', help_text='Описание домашнего задания.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Срок сдачи задания.'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text='Место в таблице лидеров.', unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='No message.', help_text='Текст уведомления.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Время окончания занятия.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Время начала занятия.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1, help_text='День недели проведения занятия.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Unnamed Subject', help_text='Название предмета.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Обратная связь от учителя.', null=True),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='submission_file',
            field=models.FileField(default='homeworks/submissions/default_submission.txt', help_text='Файл с выполненным заданием.', upload_to='homeworks/submissions/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Guest', help_text='Имя пользователя.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user_profile',
            field=models.ForeignKey(help_text='Профиль пользователя.', on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Пользователь.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа, к которой относится посещаемость.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа, к которой относится класс.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа пользователя. Только для учителей и студентов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.school'),
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(help_text='Ребёнок.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='Родитель.', limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
