# Generated by Django 5.1.1 on 2024-12-11 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_school_class_advisers_alter_achievement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='advisers',
        ),
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(help_text='Студенты, принадлежащие к классу.', limit_choices_to={'role': 'student'}, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(help_text='Учителя, ведущие класс.', limit_choices_to={'role': 'teacher'}, related_name='teaching_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Название класса, например, 5А.', max_length=10, unique=True),
        ),
    ]
