# Generated by Django 5.1.1 on 2024-12-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_class_advisers_remove_class_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Название класса, например, 5А.', max_length=100, unique=True),
        ),
    ]
