# Generated by Django 5.1.1 on 2024-12-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта (latitude) для GPS-отметки посещаемости.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота (longitude) для GPS-отметки посещаемости.', max_digits=9, null=True),
        ),
    ]
