# Generated by Django 5.1.2 on 2024-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_attendance_latitude_attendance_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, help_text='Иконка достижения.', null=True, upload_to='achievements/icons/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Примечания к посещаемости.', null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, help_text='Комментарии учителя к оценке.', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=1, help_text='Оценка студента.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='Срок сдачи задания.'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(help_text='Время окончания занятия.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(help_text='Время начала занятия.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='feedback',
            field=models.TextField(blank=True, help_text='Обратная связь от учителя.', null=True),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submittedhomework',
            name='submission_file',
            field=models.FileField(help_text='Файл с выполненным заданием.', upload_to='homeworks/submissions/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
