# Generated by Django 5.1.1 on 2024-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта школы.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота школы.', max_digits=9, null=True),
        ),
    ]
